version: '3.7'
services:
  web:
    image: skyradio-web
    container_name: skyradio-web
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NUXT_API_BASE_URL=${NUXT_API_BASE_URL}