version: '3.7'

networks:
  skyradio-network:
    external: true

services:
  web:
    image: skyradio-frontend
    container_name: skyradio-frontend
    environment:
      - NUXT_API_BASE_URL=${NUXT_API_BASE_URL}
      - ANALYTICS_HOST=${ANALYTICS_HOST}
      - ANALYTICS_KEY=${ANALYTICS_KEY}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - NODE_ENV=production
    networks:
      - skyradio-network