services:
    web:
      volumes:
        - ./.git:/app/.git
        # 
        - .devcontainer:/app/.devcontainer
        - .gitignore:/app/.gitignore
        - .env:/app/.env
        - ./docker:/app/docker
        - ./package.json:/app/package.json
        #
        - ./server:/app/server
        - ./app:/app/app

        - ./public:/app/public
        - ./nuxt.config.ts:/app/nuxt.config.ts
        # 
        - ..:/workspaces:cached
  
      command: npm run dev