version: '3.7'

networks:
  skyradio-network:
    external: true

services:
  web:
    image: skyradio-frontend
    container_name: skyradio-frontend
    environment:
      - NUXT_API_BASE_URL=${NUXT_API_BASE_URL}
      - NODE_ENV=production
    ports:
      - ${PORT}:3000
    networks:
      - skyradio-network