name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_DEPLOY }}
        logout: true
    
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile.prod --tag ghcr.io/carum98/skyradio-frontend:latest

    - name: Send to registry
      run: docker push ghcr.io/carum98/skyradio-frontend:latest

  pull-image:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Pull the image
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN_DEPLOY }} &&
          docker pull ghcr.io/carum98/skyradio-frontend:latest

  docker-run:
    runs-on: ubuntu-latest
    needs: pull-image
    environment: production
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Pull the image
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Check if container is running
          if [ "$(docker ps -q -f status=running -f name=skyradio-frontend)" ]; then
            # Stop the container
            docker stop skyradio-frontend &&
            # Remove the container
            docker rm skyradio-frontend
          fi &&
          docker run \
          --name skyradio-frontend \
          --detach \
          -e PORT=${{ secrets.PORT }} \
          -e NUXT_API_BASE_URL=${{ secrets.NUXT_API_BASE_URL }} \
          --network skyradio-network \
          ghcr.io/carum98/skyradio-frontend:latest
